[package]
name = "test_libc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime-wasi = "14.0.0"
wasmtime = "14.0.0"
anyhow = "1.0.75"
wasi = "0.11.0"